// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using trefle888.Data;

#nullable disable

namespace trefle888.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20241202214211_secondproducts")]
    partial class secondproducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("trefle888.Models.Product", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Image = "resources/suit1.jpg",
                            Name = "REGULAR FIT TRAVELER BLAZER",
                            Price = 6599.0
                        },
                        new
                        {
                            id = 2,
                            Image = "resources/suit2.jpg",
                            Name = "REGULAR FIT PREMIUM WOOL DOUBLE BREASTED BLAZER",
                            Price = 9740.0
                        },
                        new
                        {
                            id = 3,
                            Image = "resources/suit3.jpg",
                            Name = "REGULAR FIT PREMIUM WOOL BLAZER",
                            Price = 8250.0
                        },
                        new
                        {
                            id = 4,
                            Image = "~/resources/suit4.jpg",
                            Name = "SLIM FIT TRAVELER BlAZER",
                            Price = 5250.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
